### ISSUE TITLE
Error Database Connection 

### ISSUE THREAD

**Issue by andicooxy** [mr-phlames/leaf-php-boilerplate#1]
[Thu Oct 17 10:33:34 2019] PHP Warning:  Module 'exif' already loaded in Unknown on line 0
[Thu Oct 17 10:33:34 2019] PHP Warning:  Module 'mbstring' already loaded in Unknown on line 0
[Thu Oct 17 10:33:34 2019] PHP Warning:  Module 'pgsql' already loaded in Unknown on line 0
PHP 7.2.19-0ubuntu0.18.04.2 Development Server started at Thu Oct 17 10:33:34 2019
Listening on http://localhost:8000
Document root is /home/andyawuku/Documents/leaf-php-boilerplate
Press Ctrl-C to quit.
[Thu Oct 17 10:33:45 2019] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /home/andyawuku/Documents/leaf-php-boilerplate/src/config/db.php:5
Stack trace:
#0 /home/andyawuku/Documents/leaf-php-boilerplate/src/config/init.php(10): Database->connectMysqli('localhost', 'root', '', 'books')
#1 /home/andyawuku/Documents/leaf-php-boilerplate/index.php(26): require('/home/andyawuku...')
#2 {main}
  thrown in /home/andyawuku/Documents/leaf-php-boilerplate/src/config/db.php on line 5
[Thu Oct 17 10:33:45 2019] 127.0.0.1:33392 [500]: / - Uncaught Error: Call to undefined function mysqli_connect() in /home/andyawuku/Documents/leaf-php-boilerplate/src/config/db.php:5
Stack trace:
#0 /home/andyawuku/Documents/leaf-php-boilerplate/src/config/init.php(10): Database->connectMysqli('localhost', 'root', '', 'books')
#1 /home/andyawuku/Documents/leaf-php-boilerplate/index.php(26): require('/home/andyawuku...')
#2 {main}
  thrown in /home/andyawuku/Documents/leaf-php-boilerplate/src/config/db.php on line 5
[Thu Oct 17 10:33:48 2019] PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /home/andyawuku/Documents/leaf-php-boilerplate/src/config/db.php:5
Stack trace:
#0 /home/andyawuku/Documents/leaf-php-boilerplate/src/config/init.php(10): Database->connectMysqli('localhost', 'root', '', 'books')
#1 /home/andyawuku/Documents/leaf-php-boilerplate/index.php(26): require('/home/andyawuku...')
#2 {main}
  thrown in /home/andyawuku/Documents/leaf-php-boilerplate/src/config/db.php on line 5
[Thu Oct 17 10:33:48 2019] 127.0.0.1:33396 [500]: / - Uncaught Error: Call to undefined function mysqli_connect() in /home/andyawuku/Documents/leaf-php-boilerplate/src/config/db.php:5
Stack trace:
#0 /home/andyawuku/Documents/leaf-php-boilerplate/src/config/init.php(10): Database->connectMysqli('localhost', 'root', '', 'books')
#1 /home/andyawuku/Documents/leaf-php-boilerplate/index.php(26): require('/home/andyawuku...')
#2 {main}
  thrown in /home/andyawuku/Documents/leaf-php-boilerplate/src/config/db.php on line 5

**Comment by mr-phlames** [comment]
Thanks for notifying us on this error
It has been taken care of
