### ISSUE TITLE
Add support for PHP 8.1

### ISSUE THREAD

**Issue by rittjom** [mr-phlames/leaf-php-boilerplate#108]

**Comment by mychidarko** [comment]
Hi @rittjom. This has already been taken care of since the last RC. However, there's been no release since then. You can switch to leaf 3 dev for immediate support or wait for the next release. Thanks.

**Comment by mychidarko** [comment]
If you've had this issue in a previous project, pls run this:

```sh
composer require leafs/http
```

**Comment by rittjom** [comment]
everything works fine on the dev branch. thank you. sorry my fault!
