### ISSUE TITLE
Unable to start using application

### ISSUE THREAD

**Issue by ponasromas** [mr-phlames/leaf-php-boilerplate#121]
After fresh installation via composer leaf is not working. Using example code:

```
<?php

require __DIR__ . "/vendor/autoload.php";

app()->get("/", function () {
  response()->json(["message" => "Hello World!"]);
});

app()->run();
```
Getting:

`PHP Fatal error:  Uncaught Error: Call to undefined function app()`

Paths are correct. Application just does not work. Using latest version: 3.0 RC2.

P.S. Does the phpmailer should exist by default in 'vendor' directory if I did not install 'mail' module?

**Comment by mychidarko** [comment]
phpmailer is only required if you install the mail module

**Comment by mychidarko** [comment]
Also, did you install through composer or GitHub?

**Comment by ponasromas** [comment]
Yea... Project is very immature. Voided.

**Comment by mychidarko** [comment]
If you install through GitHub, the helpers aren't auto loaded for you, you'll need to link to the helpers file manually.
