### ISSUE TITLE
Database connection wrong documentation

### ISSUE THREAD

**Issue by InfinitumForm** [mr-phlames/leaf-php-boilerplate#128]
Hey guys, great framework. I just start to using it and must say, it is great job!

The documentation [using db module](https://leafphp.dev/docs/introduction/first-app.html#fetching-notes) is wrong.

`$db->connect('127.0.0.1', 'username', 'password', 'dbname');`

Need to be:

`$db->connect('127.0.0.1', 'dbname', 'username', 'password');`

The other things working just fine, I'm testing and building my app on this.

Thanks!

**Comment by mychidarko** [comment]
Hey @InfinitumForm thanks for pointing this out. It'll be corrected ASAP.

**Comment by InfinitumForm** [comment]
> Hey @InfinitumForm thanks for pointing this out. It'll be corrected ASAP.

Thank you!

Also, please explain how to use database objects `.where()`. I not find documentation but was not hard to find into PHP code.

I start building my new web app on your framework for the Geo API purposes and must say is double faster than Laravel and other frameworks I use before. It is perfect solution and when I finish I will share with you more info.

Best regards!

**Comment by mychidarko** [comment]
The references have been corrected. For the documentation on the `where` block, you can find it [here](https://leafphp.dev/modules/db/v/2/builder.html#select)
