### ISSUE TITLE
Problem when index.php is moved to public folder (like Laravel & CodeIgniter)

### ISSUE THREAD

**Issue by zerofinding** [mr-phlames/leaf-php-boilerplate#129]
router always points to base(/), how to fix it?

**Comment by mychidarko** [comment]
```php
/*
|--------------------------------------------------------------------------
| Switch to root path
|--------------------------------------------------------------------------
|
| Point to the application root directory so leaf can accurately
| resolve app paths.
|
*/
chdir(dirname(__DIR__));
```

Try this out

**Comment by zerofinding** [comment]
from leafs/skeleton
+config
+controllers
...
public
--.htaccess
--index.php
+routes
...
.htaccess


FIX
===============

(public/index.php)
...
$baseDir = dirname(__FILE__);
define('BASE__DIR', dirname($baseDir));
...
app()->setBasePath('/');
...

(config/view.php)
...
'config' => function ($config) {
	app()->template->config('path', BASE__DIR .'/'. str_replace('/', '', $config['views_path']));
},
...

(routes/_app.php)
...
app()->get('/', function () {
	response()->page(BASE__DIR . '/'. viewsPath('index.html', false));
});

app()->get('/home', 'TestsController@index');
app()->get('/test', 'TestsController@test');


:)

**Comment by mychidarko** [comment]
Hi @zerofinding. Has there been any progress with this?

**Comment by zerofinding** [comment]
> 

yay, I'm planning to use leafsphp instead of Laravel. but at the time of implementation, there are conditions that need to change the leafsphp library at the vendor. So far it works as intended (refactoring).
