### ISSUE TITLE
Negative images

### ISSUE THREAD

**Issue by ahmedaabuwarda** [mr-phlames/leaf-php-boilerplate#136]
Hello leaf,

This is soo cool. It is simple and light.
I loved it.
But I think the negative image on the Landing page is a BAD user experience.

Thanks

**Comment by mychidarko** [comment]
Thanks for pointing it out @ahmedaabuwarda

**Comment by ahmedaabuwarda** [comment]
You are welcome.

**Comment by mychidarko** [comment]
It's been fixed now, thanks
