### ISSUE TITLE
Error: Cannot use object of type Leaf\Helpers\Container as array

### ISSUE THREAD

**Issue by jeijei4** [mr-phlames/leaf-php-boilerplate#139]
https://github.com/leafsphp/leaf/blob/e9fc4e34fb1569f957babfdf38c151475c156f20/src/App.php#L168

![image](https://user-images.githubusercontent.com/21228328/188675066-cc045b28-20c2-482b-b31b-03aba95d685c.png)

**Comment by mychidarko** [comment]
See #141
