### ISSUE TITLE
Cannot use object of type Leaf\Exceptions\FrameCollection as array

### ISSUE THREAD

**Issue by jeis4n** [mr-phlames/leaf-php-boilerplate#142]
**Describe the bug**
An error occurs when generating an error:
Cannot use object as array in /vendor/leafs/exception/src/Exceptions/Inspector.php:219.

https://github.com/leafsphp/exceptions/blob/9f9728a7cbd01c1a51697dc8272a621856436f6b/src/Exceptions/Inspector.php#L219

**To Reproduce**
```php
<?php

// Undefined variable $var2.
$var1 = count($var2);
```
![image](https://user-images.githubusercontent.com/112980298/188999178-9722c45e-edf3-4b8e-8294-0f254de511c8.png)

**Expected behavior**
I was expecting the following error:
![image](https://user-images.githubusercontent.com/112980298/188999531-727b488b-ada0-4e48-8b97-0ccf3fda64b3.png)

**Additional context**
I temporarily fixed it like this, `but it needs review and testing`:

```php
<?php

219   if ( 0 < $newFrames->count() ) {
220       $newFrames->offsetGet( 0 )->addComment(
221           $previousInspector->getExceptionMessage(),
222           'Exception message:'
223       );
224   }
```

**Comment by mychidarko** [comment]
Sure, I'll look into this issue

**Comment by jeis4n** [comment]
Thank you very much!

**Comment by mychidarko** [comment]
@jeis4n This fix seems to work fine

**Comment by mychidarko** [comment]
@jeis4n You can open a PR @ https://github.com/leafsphp/exceptions
