### ISSUE TITLE
Fresh API install not working

### ISSUE THREAD

**Issue by swimitup** [mr-phlames/leaf-php-boilerplate#149]
Installed locally Leaf 3.
Created a new API project.
Run leaf serv.
The default json code do not show up:

![Screen Shot 2022-09-14 at 1 24 50 PM](https://user-images.githubusercontent.com/12404245/190244609-c85c1c5f-bb52-4aef-88b1-7802a42acc1d.png)

Code:

![Screen Shot 2022-09-14 at 1 22 52 PM](https://user-images.githubusercontent.com/12404245/190244707-252c99f5-73fe-4636-8164-387b2dbef76a.png)

Using PHP 8.1:

![Screen Shot 2022-09-14 at 1 25 54 PM](https://user-images.githubusercontent.com/12404245/190244657-becea812-8a39-4ffa-99a2-3f65a52f6a0f.png)

But if I change line 3-5 to 

```
app()->get("/", function () {
    response()->json(["message" => "Congrats!! You're on Leaf API"]);
});

```

It works:

![Screen Shot 2022-09-14 at 1 27 17 PM](https://user-images.githubusercontent.com/12404245/190244935-6b26fe70-8d63-4464-b8fa-1ad790f5e02a.png)

Could not find any restrictions to PHP 8.1, if any.

**Comment by mychidarko** [comment]
Hey @swimitup I'll check this and have it fixed ASAP. Thanks for opening this issue

**Comment by mychidarko** [comment]
This was a wrong version reference. It's been fixed in [this version](https://github.com/leafsphp/leafAPI/releases/tag/v3.0.1) of Leaf API. Your fix was the right one.
