### ISSUE TITLE
debug  = false not worked as expected

### ISSUE THREAD

**Issue by swimitup** [mr-phlames/leaf-php-boilerplate#152]
If you try to disable debug mode to not show code or more details on-screen when you got an error 500, the .env 

`APP_DEBUG=false `

or instruction

` app()->config('debug',false) `

will not prevent the nice debug screen to show up.

![Screen Shot 2022-09-26 at 2 18 30 PM](https://user-images.githubusercontent.com/12404245/192372552-70bbc639-8f0a-4751-a28b-0674ab8450f0.png)

**Comment by swimitup** [comment]
Code

`app()->config(['debug' => false]);`

will not work either.

**Comment by swimitup** [comment]
If you set debug to false in _app.php, for example, and var_dump the variable, you will get false. But if you try to var_dump the variable inside App.php class, you will get true:

![Screen Shot 2022-09-26 at 2 31 43 PM](https://user-images.githubusercontent.com/12404245/192374547-5d662d03-320d-4318-bfb8-ac3e4d2f1570.png)

`/Users/julian/uc-api/vendor/leafs/leaf/src/App.php:73:boolean true`

**Comment by swimitup** [comment]
It seems the "debug" variable is not controlled by the Config::static:$settings array, but from within the /config/app.php script:

![Screen Shot 2022-09-26 at 3 15 47 PM](https://user-images.githubusercontent.com/12404245/192382235-c8b2387c-999c-4104-9a40-d2267b58d513.png)

But still if you define the variable afterwards, in _app.php script, it will not work:

```
Leaf\Config::set([
    "views.path" => "views",
    "views.cachePath" => "views/cache",
    'log.style' => 'linux',
    'log.enabled' => true,
    'log.dir' => __DIR__ . '/../../storage/logs/',
    'log.file' => 'uc-api-'.date('Y-m-d').'.log',
    'debug' => false,
]);
```

**Comment by mychidarko** [comment]
I'll take a look at this

**Comment by mychidarko** [comment]
@swimitup  This has been fixed in Leaf's new release. You can run `composer update` in your project to get rid of this error.
