### ISSUE TITLE
response()->status(400)

### ISSUE THREAD

**Issue by swimitup** [mr-phlames/leaf-php-boilerplate#153]
Not sure if it's a bug.
According to the documentation:

>Status [#](https://leafphp.dev/#status)

>Info

>You can directly set status codes on responses, there's no need to use this method unless you want to use PHP's output methods like echo

>The HTTP response returned to the client will have a status code indicating the response’s type (e.g. 200 OK, 400 Bad Request, or 500 Server Error). You can use the Leaf application’s response object to set the HTTP response’s status like this:

>response()->status(400);
>You only need to set the response object’s status if you intend to return an HTTP response that does not have a 200 OK status. >You can just as easily fetch the response object’s current HTTP status by invoking the same method without an argument, like this:

>$status = response()->status();

If I put the following code:

```
app()->get("/", function () {
    echo response()->status(400);
});
```

It will display in browser

`HTTP/1.1 200 OK`

Not the expected

`HTTP/1.1 400 BAD REQUEST`

**Comment by mychidarko** [comment]
`status` doesn't output any information. You need to call it first and then output some information. Something like this:

```php
response()->status(400);

echo "This is the output";
```
