### ISSUE TITLE
Request not receive value when POST data = 0

### ISSUE THREAD

**Issue by quanghits** [mr-phlames/leaf-php-boilerplate#159]
Hi, 
I can't receive int value when I send POST data = 0 . 

My code: 
public function create()
{
        $data = request()->try(["pack", "app", "icon", "type", "url"]);

        if (count($data) != 5) {
            // response()->json(array("status" => false, "message" => "Params is invalid."));
            response()->json($data);
            return;
        }
}

CURL : 
curl -X POST http://localhost/leafs/themart/icon/create -d "pack=1&app=Settings&icon=SettingIconBase64&type=0&url=settings://"

Response: 
{"pack":"1","app":"Settings","icon":"SettingIconBase64","url":"settings:\/\/"} 

I can't receive value of type. :( 

Thank you!

**Comment by mychidarko** [comment]
Hi @quanghits I'll check this out

**Comment by mychidarko** [comment]
@quanghits This has been fixed. A deploy will be made available soon
