### ISSUE TITLE
[Docs] the php modules needed and docker

### ISSUE THREAD

**Issue by ampmonteiro** [mr-phlames/leaf-php-boilerplate#160]
**Is your feature request related to a problem? Please describe.**
When i was trying the framework on docker in php base container with composer,
composer  indicate error or missing zip extension

**Describe the solution you'd like**
1. on the page instalation shoud exist section about requirements by mention:
  - version of minimal php
  -  php modules needed to install the framework
2. should exist section on how install using docker, i leave here my docker file for reference:
```
FROM php:8.1-apache

RUN apt-get update && apt-get install -y \
    zlib1g-dev \
    libzip-dev

RUN docker-php-ext-install zip

RUN a2enmod rewrite && service apache2 restart

# -m -> create home
# -s -> shell acess

RUN useradd -ms /bin/bash app

WORKDIR /var/www/html

COPY --chown=app src/ .

USER app

COPY --from=composer /usr/bin/composer /usr/bin/composer

EXPOSE 80

# build: docker build -t apache-composer-pdo-php:8.1 .
# run:  docker run -d -v $(pwd):/var/www/html -p 80:80 apache-composer-pdo-php:8.1

```
**References**
Links to any libraries/frameworks doing this:
for example symfony mention the requirements : 
https://symfony.com/doc/6.0/setup.html#technical-requirements

**Additional context**
none

**Comment by mychidarko** [comment]
Hey @ampmonteiro. Thanks for opening this issue. We'll add something like this.

**Comment by mychidarko** [comment]
This has been completed.
