### ISSUE TITLE
[Docs] Finish up tutorial

### ISSUE THREAD

**Issue by cr34t1ve** [mr-phlames/leaf-php-boilerplate#161]
@mychidarko The current repl tutorial ends at Working with files . Can the tutorial be completed? It feels like the essentials of leaf are missing

**Comment by mychidarko** [comment]
@cr34t1ve can you work on the description 🙏🏽

**Comment by cr34t1ve** [comment]
@mychidarko The current repl tutorial ends at _Working with files_ . Can the tutorial be completed? It feels like the essentials of leaf are missing

**Comment by mychidarko** [comment]
This has been fixed now. https://github.com/leafsphp/docs/pull/38
