### ISSUE TITLE
URL params in POST request has bug. 

### ISSUE THREAD

**Issue by quanghits** [mr-phlames/leaf-php-boilerplate#166]
**Describe the bug**
I send an url with special characters like &. Example: https://example.com/?look=a&real=B 
And i receive value: https://example.com/?look=a&amp;amp;real=B 

URL encoded wrong.  As above, "&" has been encoded to "**&amp;amp;amp;**"  
Thank you!

**Comment by mychidarko** [comment]
Hi @quanghits. You can turn the encoding off. Just pass `false` as a second parameter to `get`

**Comment by mychidarko** [comment]
@quanghits there's not enough information to replicate your error. I've tried your URL as a post request and the encoding is correct. Turning off the encoding works fine as well. Some fixes have however been pushed for urlencoded data

<img width="406" alt="image" src="https://user-images.githubusercontent.com/26604242/209198851-db93974e-1485-4ce4-b07c-a243bca97eed.png">

You can reopen the issue with more context, thanks
