### ISSUE TITLE
Boilerplate: Leaf with the Hexagonal Architecture pattern and Domain-Driven Design

### ISSUE THREAD

**Issue by jeijei4** [mr-phlames/leaf-php-boilerplate#168]
**Describe the solution you'd like**
I would like a boilerplate using Leaf with the Hexagonal Architecture pattern and Domain-Driven Design (without MVC).

**References**
*The following example uses symfony 6, but I would like to remove symfony and use Leaf instead*:
[CodelyTV - hexagonal architecture](https://github.com/CodelyTV/php-ddd-example#-hexagonal-architecture)

**Comment by mychidarko** [comment]
Currently, this isn't something we're looking at investing in. Maybe when there's more time
