### ISSUE TITLE
Middleware route option not working in group 

### ISSUE THREAD

**Issue by Jonas-Bostoen** [mr-phlames/leaf-php-boilerplate#172]
**Describe the bug**
I've been looking at implementing middleware in my API, I'm using route groups to split up my requests. But if I add the middleware option to one of the routes in the group, it doesn't get executed. Although without the group it works fine.

**To Reproduce**
**Code examples**

```php
require_once __DIR__ . '/../middleware/isAuthenticated.php';

// Does not execute middleware
$app->group("/test",  function () use ($app, $isAuthenticated) {
    $app->get('/', ['middleware' => $isAuthenticated,  function () {
      response()->json(['test' => 'authenticated']);
    }]);
  });

// Does execute middleware
$app->get('/test', ['middleware' => $isAuthenticated,  function () {
    response()->json(['test' => 'authenticated']);
}]);
```

**Expected behavior**
The grouped routes should behave the same as the normal routes when it comes to middleware.

**Additional context**
I don't know if this is a feature or a bug, I couldn't find any context about this behaviour in the documentation. Thanks in advance!

**Comment by mychidarko** [comment]
Hi @Jonas-Bostoen 

Thanks for opening this issue. I'll take a look at this. The expected behaviour is as you described. It should work the same with or without the group

**Comment by mychidarko** [comment]
@Jonas-Bostoen this issue has been fixed. You can run `leaf install router` or `composer require leafs/router` to update Leaf router and fix this issue on your end
