### ISSUE TITLE
I can't seem to get the 'app.down' config to be acknowledged.

### ISSUE THREAD

**Issue by mychidarko** [mr-phlames/leaf-php-boilerplate#184]
I can't seem to get the 'app.down' config to be acknowledged.
```php
<?php

use Leaf\App;

require __DIR__ . '/vendor/autoload.php';

$app = new App([
    'app.down' => true
]);

// these don't work either
// $app->config('app.down', true);
// $app->configure([
//     'app.down' => true
// ]);

$app->get('/', function () use ($app) {
    $app->response()->json(Leaf\Config::get('app'));
});

$app->run();
```

_Originally posted by @kczx3 in https://github.com/leafsphp/leaf/discussions/37#discussioncomment-5218327_

**Comment by mychidarko** [comment]
@kczx3, I've opened an issue here. I'll keep this thread updated

**Comment by kczx3** [comment]
Awesome, many thanks!

**Comment by mychidarko** [comment]
This has been fixed now @kczx3. You can run `leaf install leaf` or `composer require leafs/leaf` to update to the latest version.

**Comment by kczx3** [comment]
Works now!  Thank you again!

**Comment by mychidarko** [comment]
Awesome 🚀
