### ISSUE TITLE
Basic template doesn't work

### ISSUE THREAD

**Issue by nricciardi** [mr-phlames/leaf-php-boilerplate#189]
I'm trying to use the basic template to create a simple app to expose some functionality, but when I upload project files on remote webserver hosted by Altervista and I try to access on a defined route, the server response me with a 500 error.
I'm debugging and now I know that the problem is in the autoload, in particular when Leaf call the static composer method after require in autoload.php

How fix it?

**Comment by mychidarko** [comment]
Can you share the exact error you're getting?

**Comment by nricciardi** [comment]
*mysite* it is currently unable to handle the request.
HTTP ERROR 500

**Comment by mychidarko** [comment]
I get that, but is there any error thrown or a log I can look at? Error 500 doesn't say much

**Comment by nricciardi** [comment]
I'm sorry but I'm hosting my project on an host which couldn't show me log...

However, when I run _leaf serve_ in local everything works fine.

**Comment by mychidarko** [comment]
Without seeing the log or error, there's no way to determine what exactly is happening on the system

**Comment by mychidarko** [comment]
Unfortunately, I'll need more information to be able to do anything about this

**Comment by milosPavic** [comment]
> I'm sorry but I'm hosting my project on an host which couldn't show me log...
> 
> However, when I run _leaf serve_ in local everything works fine.

Host always show error log but you need to read docs where it is, or how to enable it and where it is.

**Comment by nricciardi** [comment]
Could .htaccess be the cause of problem?
Using default .htaccess of my host I see welcome.html page (other routes no), but with the leaf htaccess get error 500

**Comment by mychidarko** [comment]
That's very likely @nricciardi

**Comment by nricciardi** [comment]
I'm just fixing that problem, it was htaccess. In particular, my host use htaccess to set php version, so when I overwrite htaccess the server return to use php7 instead of 8...

**Comment by mychidarko** [comment]
Hi @nricciardi, just checking in on this issue

**Comment by nricciardi** [comment]
> Hi @nricciardi, just checking in on this issue

Thanks you, but it wasn't a leaf problem in the end

**Comment by mychidarko** [comment]
Awesome, can you share your solution here just in case anyone else runs into the same problem

**Comment by nricciardi** [comment]
Sure!
The only problem is that this code doesn't work if you navigate to the root, but only if you enter the route public, api, etc

```python
# # av:php5-engine
AddHandler av-php82 .php

# av:PHP-upload
php_value upload_max_filesize 20M
php_value post_max_size 20M
php_value max_input_time 300
# PHP-upload

<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews -Indexes
    </IfModule>

    RewriteEngine On

    # Handle Authorization Header
    RewriteCond %{HTTP:Authorization} .
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} (.+)/$
    RewriteRule ^ %1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ /public/index.php [L]
</IfModule>
```
