### ISSUE TITLE
RoadRunner or Swoole support?

### ISSUE THREAD

**Issue by darakanoit** [mr-phlames/leaf-php-boilerplate#198]
Is the possibility of integrating such tools as "roadrunner\swoole" in the future being considered?

**Comment by mychidarko** [comment]
Hi @darakanoit. We’ve already started playing with Swoole support with our [Eien server](https://github.com/leafsphp/eien).  Unfortunately, we have some more pressing issues, so we can't yet hop on to working with Roadrunner.

**Comment by darakanoit** [comment]
thanks for the answer

**Comment by darakanoit** [comment]
thanks for the answer

**Comment by joanhey** [comment]
Benchmark LeafPHP with nginx and Adapterman. #204
https://github.com/joanhey/AdapterMan

![image](https://github.com/leafsphp/leaf/assets/249085/265520cd-03a8-4cba-9634-b2e684c55d24)
Actual benchmark running:
https://www.techempower.com/benchmarks/#section=test&runid=473fbd63-e8ff-4082-919e-dd1be6f2a716&test=json
Later I'll try to add Eien Server to the benchmark. And db tests.
