### ISSUE TITLE
Leaf development status

### ISSUE THREAD

**Issue by fatherofinvention** [mr-phlames/leaf-php-boilerplate#239]
Leaf looks like a great framework, but I noticed there isn't any activity in the discord, the blog hasn't been updated in over a year, and several issues posted months ago haven't gotten any response from the core team. So is Leaf PHP abandoned, or is there some other reason for the lack of updates? What is on the roadmap for Leaf in 2024?

**Comment by mychidarko** [comment]
Hi @fatherofinvention work on Leaf has been slow for the first half of the year because the team was caught up with our day jobs and personally for health reasons. I've pretty much recovered and work should pick up again soon. Leaf isn't disappearing anytime soon 🤞🏽
