### ISSUE TITLE
After upgrade to Leaf 3.7.1 from 3.5 started Leaf::View or CSRF errors

### ISSUE THREAD

**Issue by VT-nkumar** [mr-phlames/leaf-php-boilerplate#262]
## Describe the bug

After upgrading to 3.7.1 then it started showing Leaf View error (class not found).   After commenting that line in index.php then it started throwing install CSRF.   After installing CSRF then it started showing token missing error.

## To Reproduce

Install 3.5 version then upgrade to 3.7.1 (latest version)

## Expected behavior

It must upgrade without any issues.  If any changes required then it is better to mention in documentation clearly

**Comment by mychidarko** [comment]
Hi @VT-nkumar no extra changes should be required to update Leaf on it's own, but for context, are you using Leaf MVC?

**Comment by mychidarko** [comment]
If you are using Leaf MVC, can you make sure that all modules are also updated to the latest version?

**Comment by mychidarko** [comment]
For the Leaf\View line in the index.php file, you will need to change that to `Leaf\Config::attachView(\Leaf\Blade::class);`

And if you run into any other view issues, you can refer to this file https://github.com/leafsphp/leafMVC/blob/v3.x/config/view.php

**Comment by mychidarko** [comment]
Hi @VT-nkumar, checking up on this issue

**Comment by falvarador** [comment]
Hello. I have the same issue, but in my case, I am creating a new app from scratch using the Leaf CLI and the MVC template. When I run the app, I have the same error. Please help

**Comment by mychidarko** [comment]
@falvarador can you pls paste the full error in here?

**Comment by mychidarko** [comment]
And can you pls make sure all your other modules are up to date, especially mvc-core

**Comment by falvarador** [comment]
I think everything is up to date and this is the error. The error appears when I use BareUI; otherwise, the application works fine with Blade.

![image](https://github.com/user-attachments/assets/86ff2f27-a4ae-42f1-b3f8-fcc64986a5c1)

**Comment by mychidarko** [comment]
Got it, thanks. I'll take a look at this. Can I see your `config/view.php` file?

**Comment by mychidarko** [comment]
@falvarador I just published a new version of Bare UI. Can you check if this fixes your issue?

**Comment by falvarador** [comment]
Hello, works fine now. Thanks a lot
Another question: Leaf supports PHP 8.4?

**Comment by mychidarko** [comment]
It does, but there are a few warnings you may get. Your app will still work fine though, I'll be releasing a new version to get rid of the warnings
