### ISSUE TITLE
CSRF breaks Auth on dynamic routes

### ISSUE THREAD

**Issue by timclutton** [mr-phlames/leaf-php-boilerplate#268]
There seems to be an incompatibility between `leafs/csrf` and `leafs/auth` that causes authentication middleware not to run when using dynamic routing.

A minimal example:

    require __DIR__ . '/vendor/autoload.php';

    auth()->middleware('auth.required', function () {
        response()->exit(['unauthorised'], 401);
    });

    app()->get('/secure', [
        'middleware' => 'auth.required',
        function () {
            response()->json(['message' => 'Hello World!']);
        }
    ]);

    app()->get('/{insecure}', [
        'middleware' => 'auth.required',
        function ($insecure) {
            response()->json(['message' => "Uh oh!"]);
        }
    ]);

    app()->csrf();

    app()->run();

Using the above, a GET call to `/secure` will return a 401 error as expected.

But a GET call to `/insecure` (or since it's dynamic, anything that isn't `/secure`) will unexpectedly return:

    {"message":"Uh oh!"}

Simply commenting out, or removing, the line `app()->csrf()` and repeating the GET call to `/insecure` will return a 401 error as expected.

Versions in use:

- leafs/auth: 3.0.3
- leafs/csrf: 0.5.3
- leafs/leaf: 3.8

**Comment by ibnsultan** [comment]
Hi @timclutton, few queries
- are you using leafMVC or you've installed leaf modules as independent packages
- could you please show an example to your csrf usecase, i.e your csrf setup

**Comment by timclutton** [comment]
Hi @ibnsultan,

I was using LeafMVC when I came across this, but I stripped everything out (until I had the minimal code above) trying to isolate the issue. (I'm new to Leaf so I'm trying to understand how everything fits together.)

The CSRF usage is as simple as calling `app()->csrf();` in the above code, and then calling `csrf()->form()` in my HTML.

One thing I would note is that clearly there's no way to authenticate via the above code, so I'd expect every response to always be a 401.

Thanks for looking at this.

**Comment by ibnsultan** [comment]
could you please look at this [issue](https://github.com/leafsphp/leaf/issues/264)

Let me know if this has/hasn't resolves your issue!

**Comment by timclutton** [comment]
I'm not sure how that applies as I'm not using exemptions in the CSRF config.

**Comment by mychidarko** [comment]
@timclutton I've been able to replicate your issue, thanks for being so detailed. It had to do with the way Leaf prioritizes middleware stacks internally. I'm rolling out a new version which should fix your issue

**Comment by mychidarko** [comment]
Done, updating your leaf version should fix your issue

**Comment by timclutton** [comment]
Looks good 👍
