### ISSUE TITLE
DELETE /photos/{id} and PUT /photos/{id} not working

### ISSUE THREAD

**Issue by patrickvuarnoz** [mr-phlames/leaf-php-boilerplate#270]
## Describe the bug

In the online documentation it says that the path to use for a `DELETE` request should be `DELETE /photos/{id}`, see https://leafphp.dev/docs/mvc/controllers.html#resource-controllers. But the code base from the router does not handle this route. Instead it expects a the request as `DELETE /photos/{id}/delete`. 

In the code base the corresponding line in `Router::resource()` looks like this:
`static::match('POST|DELETE', "$pattern/{id}/delete", "$controller@destroy");`

The same (not yet tested) seems to be true for `update` method:
`static::match('POST|PUT|PATCH', "$pattern/{id}/edit", "$controller@update");`

## Expected behavior

The expected behaviour would be that it works as documented, i.e. as `DELETE /photos/{id}` and `PUT /photos/{id}`. I do unterstand that if the client does not support the special HTTP verbs for DELETE/PUT/PATCH that it might be necessary to allow `POST /photos/{id}/delete`. But for a client that supports it, it is much more logic to use the short format `DELETE /photos/{id}`.

In my opinion, the matching in `Router::resource()` should look like this:
````
// Normal matching for clients that support all http verbs
static::match('GET|HEAD', $pattern, "$controller@index");
static::post($pattern, "$controller@store");
static::match('GET|HEAD', "$pattern/create", "$controller@create");
static::match('DELETE', "$pattern/{id}", "$controller@destroy");
static::match('PUT|PATCH', "$pattern/{id}", "$controller@update");
static::match('GET|HEAD', "$pattern/{id}/edit", "$controller@edit");
static::match('GET|HEAD', "$pattern/{id}", "$controller@show");

// Additional matching for clients that DO NOT support all http verbs
static::match('POST', "$pattern/{id}/delete", "$controller@destroy");
static::match('POST', "$pattern/{id}/edit", "$controller@update");
````

Additionally I think you should document these two special routes `POST /photos/{id}/delete` and `POST /photos/{id}/edit` in the online documentation for those people looking for it and having a client that does not support all HTTP verbs.

Alternatively you might want to look into the `X-HTTP-Method-Override` HTTP header which is a common way of sending POST requests instead of DELETE/PUT/PATCH and telling the server which HTTP method it should actually use.

**Comment by mychidarko** [comment]
Nice catch @patrickvuarnoz. I'll release a patch for this. Supporting those clients is no longer as much of a priority as when this was first released

**Comment by mychidarko** [comment]
Closing this as fixed. I added the new routes, but kept the old ones for those who happen to have used them
