### ISSUE TITLE
Fatal error: Uncaught InvalidArgumentException: Unsupported driver

### ISSUE THREAD

**Issue by wfsdaj** [mr-phlames/leaf-php-boilerplate#35]
I am a Chinese user, can not speak English, or a PHP rookie, this is using Google automatic translation, I apologize first. I encountered an error using the model, What did I do wrong?

> Fatal error: Uncaught InvalidArgumentException: Unsupported driver 

My program code:

App\Controllers\UserController.php
```php
namespace App\Controllers;

use Leaf\Controller;
use App\Models\User;

class UsersController extends Controller
{
    public function index()
    {
        $users = User::all();
        foreach ($users as $user) {
            echo $user->name;
        }
    }
```

App\Models\User.php
```php
namespace App\Models;

use Leaf\Model;

class User extends Model
{
    protected $table = 'users';
    public $timestamps = false;
}
```

My database connection：
```php
$db = new Leaf\Db("localhost", "root", "root", "demo");
```

**Comment by mychidarko** [comment]
Hi @wfsdaj, thanks for trying out Leaf. First of all, can you give me some information on your setup? Are you using Leaf on it's own or something like Leaf MVC/Leaf API?

**Comment by mychidarko** [comment]
Also, Leaf Models run on eloquent, and not `Leaf DB`, that may be one of the reasons you're encountering this problem, but I can't say so just yet, which is why I need a more information on your setup

**Comment by wfsdaj** [comment]
@mr-phlames thank you for your reply. I use Leaf. I can use the db class normally on the index page.

leaf/index.php

```php
require __DIR__ . "/vendor/autoload.php";
$app = new Leaf\App();
require __DIR__ . "/config/app.php";
require __DIR__ . "/app/routes.php";

$users = $db->select("users", "id, name")->fetchObj();
echo $users->id;        //output 1

$app->run();
```

**Comment by mychidarko** [comment]
Yes the DB class just provides a simple way to use your database. Something you can work with anywhere in your code without worrying about models and stuff like that. So in that case, is you problem resolved or do you still have issues with the database?

**Comment by wfsdaj** [comment]
Yes, there are still errors. 😅

**Comment by mychidarko** [comment]
Can you confirm something for me? Do you have a `.env` file in your setup?

**Comment by wfsdaj** [comment]
my /.env file

```
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=demo
DB_USERNAME=root
DB_PASSWORD=root
```

my /config/app.php

```php
$app->config([
    'mode' => 'development',
    'debug' => true,
    'templates.path' => './views',
    'log.enabled' => true,
    'cookies.path' => '/',
    'cookies.encrypt' => true,
    'cookies.lifetime' => '20 minutes',
]);
```

**Comment by mychidarko** [comment]
And are you correctly loading the `.env` variables into your code?

**Comment by wfsdaj** [comment]
I thought the .env file was automatically loaded just like laravel。
How can I load .env file correctly?  require vlucas/phpdotenv？

**Comment by mychidarko** [comment]
Yeah, that should be the easiest way.

Env files are loaded automatically only if you use something like leaf MVC or leaf API.
