### ISSUE TITLE
Optional patterns: empty first parameter

### ISSUE THREAD

**Issue by m1ga** [mr-phlames/leaf-php-boilerplate#36]
When calling this route:
```
$app->get('/messages/(\d+)(/\d+)?', function ($id, $date = 0) use($app) {
    $app->response->respond($id);
});
```
with `/messages/2` the output/$id is empty. When calling it with `/messages/2/34` it will correctly output 2.

Same happens with the blog route from the example: https://leafphp.netlify.app/#/2.1/routing/sub-patterns. When I add year output like this:
```
$leaf->get('/blog(/\d+)?(/\d+)?(/\d+)?(/[a-z0-9_-]+)?', function($year = null, $month = null, $day = null, $slug = null) {
  if (!$year) { echo "Blog overview $year"; return; }
  if (!$month) { echo "Blog year overview $year"; return; }
  if (!$day) { echo 'Blog month overview'; return; }
  if (!$slug) { echo 'Blog day overview'; return; }
  echo 'Blogpost ' . htmlentities($slug) . ' detail';
});
```
it will be empty when calling it with one number only.

Is there a way to get the get the first parameter?

**Comment by mychidarko** [comment]
Hi @m1ga thanks for using leaf and sorry for the delayed response. I believe this is a little problem with the routing system😫 For now, I'd recommend you use another router in your leaf project if you do not find a work around for it.

You can look [here](https://leafphp.netlify.app/#/lucky-charm/routing/?id=%f0%9f%91%8b-using-a-different-router) for an overview on using other routers.

Thanks and sorry once again 😔

**Comment by m1ga** [comment]
@mr-phlames thanks for the feedback! I'll try that and give you feedback :+1:
