### ISSUE TITLE
$app->response->respond in index.php:13 does not work

### ISSUE THREAD

**Issue by nkrumahthis** [mr-phlames/leaf-php-boilerplate#39]
$app->response->respond does not exist.
Fatal error: Uncaught Error: Call to undefined method Leaf\Http\Response::respond()

I tried to help by creating the respond($data) function in Respond.php but it wouldn't work.

Please be kind, as I'm still figuring stuff out.

**Comment by mychidarko** [comment]
Hi @nkrumahthis Response::response has been deprecated in the latest versions of Leaf, so you'll have to use $app->response->json instead. You can find out more on this [here](https://leafphp.netlify.app/#/leaf/v/2.4/http/response?id=json). Sorry for not making this clear
