### ISSUE TITLE
\Leaf\Util::sanitize null values

### ISSUE THREAD

**Issue by chatelain** [mr-phlames/leaf-php-boilerplate#40]
Hello,

I have start a new project with the last leaf.php version.
Very nice growing seed.

I had a problem with the sanitize function, used to get values from http request body.
Getting the null value is very useful I think

Do you think this fix can cause any issues ?
\Leaf\Util::sanitize
L.22    $data = is_null($data) ? null : htmlspecialchars($data, ENT_QUOTES, 'UTF-8');

Thank you
Best regards

**Comment by mychidarko** [comment]
Hi @chatelain, nice to hear from you again. Actually, `Util::sanitize` doesn't get values from the request body, it simply sanitizes it, and provides some basic security for the data passed into it. So, by the time this method is called, the data from the request has already been retrieved.

The `Leaf\Http\Request` handles the data just as you said above. If the data isn't found it returns `null`. I hope this was useful for you, and good luck with your project😃
