### ISSUE TITLE
Support of sqlite3 in LeafDB

### ISSUE THREAD

**Issue by tisseurdetoile** [mr-phlames/leaf-php-boilerplate#41]
Hello,

It's not a bug it's a feature request.

Do you plan to add the support of sqlite3 un LeafDB ?

Have a nice day.

**Comment by mychidarko** [comment]
Hi @tisseurdetoile, thanks for reaching out. I indeed plan on adding sqlite support in Leaf DB in the future, however it may take some time to implement due to other activities like school😭

If however, you want to personally implement this, I'll be glad to see a pull request from you. Thanks.

**Comment by tisseurdetoile** [comment]
thanks for you reply.
Good luck with school.
