### ISSUE TITLE
Response from GET Request Return as Null

### ISSUE THREAD

**Issue by randytan** [mr-phlames/leaf-php-boilerplate#42]
Hi there,

We're following the main tutorial to obtain the GET parameter from the URL and output it to a JSON response.
```
$app->get("/user", function() use($app) {

  $name = $app->request()->get("name");
  $app->response()->json([
    "name" => $name,
    "day" => "test"
  ]);

});
```

Expected response should be like this:
`curl -X GET http://localhost/user?name=test`
```
{
    "name": test,
    "day": "test"
}
```

But it keeps throwing out null as the response.

```
{
    "name": null,
    "day": "test"
}
```

More information: php-7.4.16 / nginx 1.18.0

Thank you.

**Comment by mychidarko** [comment]
Hi @randytan, I'll like you to try a few things out for me. Can you pls output `$app->request()->body()` and also  `$_GET["name"]`.

**Comment by randytan** [comment]
Hi @darko-mychi 

Sorry for late response.
Output from` $app->request()-body();`

```
$app->get("/user", function() use($app) {

  $name = $app->request()->body();
  $app->response()->json([
    "name" => $name,
    "day" => "test"
  ]);

});
```

is `{"name":[],"day":"test"}`

For the `$_GET["name"]` is

```
Type: ErrorException
'
Code: 8
Message: Undefined index: name
File: D:\Dev\nginx-1.18.0\www\index.php
Line: 17
```

**Comment by mychidarko** [comment]
Wait a minute😅 I noticed your code contains `$app->get`, but you're using `-X POST`. With -X, you're actually ending up changing the method although it will still behave like a GET request.

I got this to work by simply sending `curl http://localhost:8080/user?name=lol`:

```
{"name":"lol","day":"test"}
```

**Comment by randytan** [comment]
Hi @darko-mychi 

Sorry typo on my end. I have changed the curl command above. I opened the localhost url via browser also get the same empty[] response from leaf.

Thank you.

**Comment by mychidarko** [comment]
Can you pls post your full code?
