### ISSUE TITLE
Before route middleware not working in v2.4.4

### ISSUE THREAD

**Issue by ivan-au** [mr-phlames/leaf-php-boilerplate#45]
The before route middleware doesn't work as [indicated in v2.4.4 documentation](https://leafphp.netlify.app/#/leaf/v/2.4.4/routing/middleware). The code below generates error `Call to undefined method Leaf\App::before()`
```
$app->before('GET', '/.*', function() {
    // ... this will always be executed
});
```

**Comment by mychidarko** [comment]
Hi @ivan-au, thanks for pointing this out. I'm sorry, this escaped me in the recent versions. In the meantime, you can use `$app->add` to load in a middleware which will run before your app does. A permanent fix will be made in the next release. Thanks.
