### ISSUE TITLE
PHP 8 Support?

### ISSUE THREAD

**Issue by bogordesaincom** [mr-phlames/leaf-php-boilerplate#46]
When Leaf PHP support php 8?

```
  [InvalidArgumentException]
  Package leafs/cli has a PHP requirement incompatible with your PHP version,
   PHP extensions and Composer version
```

**Comment by mychidarko** [comment]
Hi @bogordesaincom, all other leaf packages will be updated to support php 8 in one of our upcoming releases. However, for now, you can go ahead to directly install Leaf without relying on Leaf CLI.

You can just use composer directly

```sh
composer require leafs/leaf
```

Or use Leaf MVC or Leaf API. Thanks☺️
