### ISSUE TITLE
Auth - register

### ISSUE THREAD

**Issue by DominikJoppa** [mr-phlames/leaf-php-boilerplate#48]
Hi,

I did the registration through authorization and I get this error message.

Can you help me with that?

POST:
`{
    "username": "admin",
    "email": "admin@admin.com",
    "password": "s"
}
`

Error:
`{
    "error": {
        "dev": "Call to a member function bind_param() on bool"
    },
    "code": 500
}`

Code:
```
$app->post('/register', function () use ($app, $form, $auth) {
        $username = $app->request()->get("username");
        $email = $app->request()->get("email");
        $password = $app->request()->get("password");

        $validation = $form->validate([
            "username" => "username",
            "email" => "email",
            "password" => "required"
        ]);

        if (!$validation) $app->response()->throwErr($form->errors());


        $user = $auth->register("users", [
            "username" => $username,
            "email" => $email,
            "password" => $password
        ]);

        if (!$user) $app->response()->throwErr($auth->errors());
        $app->response()->json($user);
    });
```

**Comment by DominikJoppa** [comment]
My fault.

I forgot to add created_at and updated_at to the table.

**Comment by mychidarko** [comment]
Also, if you don't want to add the `created_at` and `updated_at` columns, you can just configure auth with use_timestamps false. See https://leafphp.netlify.app/#/leaf/v/2.5.0/core/auth?id=settings for the details.
