### ISSUE TITLE
Issue with charset and collation if mssing from the .env file

### ISSUE THREAD

**Issue by pjotrsavitski** [mr-phlames/leaf-php-boilerplate#49]
If `DB_CHARSET` or `DB_COLLATION` are missing from the `.env` file, then running console commands will fail with `SQLSTATE[42000]: Syntax error or access violation: 1115 Unknown character set: ''`.

The lines of code to have a default value set in case it is missing or empty don't seem to work as expected:
https://github.com/leafsphp/leaf/blob/v2.x/src/Database.php#L23

The exception clearly indicates that empty value is used instead.

**Comment by mychidarko** [comment]
Thanks for the pull😇
