### ISSUE TITLE
Request > Paths

### ISSUE THREAD

**Issue by jamie-syon** [mr-phlames/leaf-php-boilerplate#52]
I'm looking at the "Paths" section here: https://leafphp.netlify.app/#/leaf/v/2.5.0/http/request

As far as I can see the methods for "getRootUri" and "getResourceUri" have yet to be implemented?  Is that correct?

**Comment by mychidarko** [comment]
Hi @jamie-syon, `Request::getRootUri` and `Request::getResourceUri` were aliases for `Request::getScriptName` and `Request::getPathInfo` respectively and were removed after the v2.1 release. It was a blunder on my part as I forgot to remove these references in the docs. Thanks for pointing this out. I'll have this fixed soon.

**Comment by aanders77** [comment]
The references are still there, at the bottom of the page.

**Comment by mychidarko** [comment]
Fixed now😇
