### ISSUE TITLE
Leaf\Flash::display($key) will throw error if $key has not been set 

### ISSUE THREAD

**Issue by ivan-au** [mr-phlames/leaf-php-boilerplate#53]
### How to reproduce issue
When using static method `Leaf\Flash::display($key)` when `$key` has not been previously set via `\Leaf\Flash::set`, Leaf will throw an error.

### Suggested solution
Modify `Leaf\Flash::display($key)` to return null if `$key` can't be found

**Comment by mychidarko** [comment]
Hi @ivan-au. Thanks for pointing this out. This will be fixed soon.👍🔥
