### ISSUE TITLE
Migrations fail

### ISSUE THREAD

**Issue by jhintringer** [mr-phlames/leaf-php-boilerplate#54]
Hy there. I can't get Migrations running with LeafAPI. It always breaks with error on line 14 (var capsule is invalid).
`php leaf db:install` worked and the database was created successfully.
`php leaf db:migrate` fails.

![leaf_db_migrate_error_capsule](https://user-images.githubusercontent.com/9859818/134201535-fdba1541-167f-4127-a1a7-55a365432291.jpg)

Can you help me with this? Thanks a lot!

Versions, i'm using:
- PHP 8
- Leaf 2.6.0
- Aloe 1.1.0

**Edit//**
It seems to be related to last commit https://github.com/leafsphp/leaf/commit/0ca6097f63b561199272765f3a2b625d0f516857
Maybe a dependency conflict?

**Comment by mychidarko** [comment]
Hi @jhintringer, sorry about this.  You're right about Leaf v2.6 being the problem, Leaf API is actually supposed to receive an update which hasn't been published yet, so until that's done, pls revert to the prior version of Leaf. Thanks for pointing this out.
