### ISSUE TITLE
Malformed JWT

### ISSUE THREAD

**Issue by OtaHofmann** [mr-phlames/leaf-php-boilerplate#84]
**Describe the bug**
I just found out that there is a problem with the deformed JWT. 
The JWT library throws an error that must be caught.

I found a problem in Authentication.php: 116 (version 2.X)
You can fix it as follows.

try {
  $payload = JWT::decode ($ token, $ secretPhrase, ['HS256']);
  if ($ payload! == null) return $ payload;
} catch (\ DomainException $ exception) {
  self :: $ errorsArray ["token"] = "Malformed token";
}

Thank you so much :-)

**To Reproduce**
1. Send malformed JWT

**Expected behavior**
40x response

**Comment by mychidarko** [comment]
Hi @OtaHofmann. Thanks, I'll look into this and have it resolved 🙏

**Comment by mychidarko** [comment]
Fixed in v3 and will also be available in the next v2 release 😇
