### ISSUE TITLE
Is Leaf tested?

### ISSUE THREAD

**Issue by pabloelcolombiano** [mr-phlames/leaf-php-boilerplate#88]
Hello!

Thanks for your work.

My colleagues and I are willing to give Leaf a try. However I cannot see any tests. Is the framework tested in some ways?

**Comment by mychidarko** [comment]
Hi @pabloelcolombiano. There are no written tests in the project as of now, however, we do plan to include tests in the next release. And with the inclusion of modules, each piece of code will be well tested.

For now, however, Leaf has had thousands of downloads from composer alone, most of which build real-world apps and APIs. Also, we always make sure to test Leaf over and over in production-ready apps to quickly and efficiently catch bugs. I do encourage you to give it a try 😊

**Comment by mychidarko** [comment]
Hi @pabloelcolombiano, just as promised, tests have been pushed on v3, more are being written as well.
